#!/usr/bin/env python3
"""
Generates a real, book-formatted PDF volume of the archive — cover, table
of contents with real page numbers, one chapter per entry, running headers,
page numbers — not a rendered webpage. This is the "readable without git
skills, by anyone who downloads it" durability backup: the git repo is
already the real backup, this is the human-facing one.

Triggered every VOLUME_SIZE entries (see build.yml), not on every publish:
Volume 1 = Days 1-100, Volume 2 = Days 101-200, etc. Idempotent — skips if
that volume's PDF already exists — and deliberately isolated from the daily
publish pipeline (its own CI step, its own dependency) since WeasyPrint is
too heavy to install on every push for a job that only matters once every
hundred days.

Reuses build_pages.py's render_body() so a chapter's paragraph rhythm
(pause/sequence/grouped, Mirror/Think markers) is generated by the exact
same logic as the live site — one rhythm engine, not two to keep in sync.
"""
import json
import sys
from pathlib import Path

from weasyprint import HTML, CSS

sys.path.insert(0, str(Path(__file__).parent))
from build_pages import render_body, format_themes, format_date, escape_html, escape_attr  # noqa: E402

ROOT = Path(__file__).parent.parent
ENTRIES_JSON = ROOT / "entries.json"
FONTS_DIR = ROOT / "fonts"
BACKUPS_DIR = ROOT / "backups"

VOLUME_SIZE = 100
AUTHOR = "Sujeeth Talluri"
ETHOS = "Truth reveals who God is. This helps me discover who I am."
ABOUT = (
    "Every morning I spend time in quiet reflection, then write one honest "
    "piece — not a lesson, not advice, just an observation about ordinary "
    "life that I hope makes you pause and ask the same question I had to "
    "ask myself: what does this reveal about me? This volume exists so "
    "these reflections outlast any single app, platform, or year."
)


def font_uri(filename):
    return (FONTS_DIR / filename).resolve().as_uri()


def build_css():
    return f"""
    @font-face {{
      font-family: 'Fraunces'; src: url('{font_uri("Fraunces-Variable.ttf")}');
      font-weight: 100 900; font-style: normal;
    }}
    @font-face {{
      font-family: 'Fraunces'; src: url('{font_uri("Fraunces-Italic-Variable.ttf")}');
      font-weight: 100 900; font-style: italic;
    }}
    @font-face {{
      font-family: 'Source Serif 4'; src: url('{font_uri("SourceSerif4-Variable.ttf")}');
      font-weight: 200 900; font-style: normal;
    }}
    @font-face {{
      font-family: 'Source Serif 4'; src: url('{font_uri("SourceSerif4-Italic-Variable.ttf")}');
      font-weight: 200 900; font-style: italic;
    }}
    @font-face {{
      font-family: 'IBM Plex Mono'; src: url('{font_uri("IBMPlexMono-Regular.ttf")}');
      font-weight: 400; font-style: normal;
    }}
    @font-face {{
      font-family: 'IBM Plex Mono'; src: url('{font_uri("IBMPlexMono-Medium.ttf")}');
      font-weight: 500; font-style: normal;
    }}
    @font-face {{
      font-family: 'IBM Plex Mono'; src: url('{font_uri("IBMPlexMono-SemiBold.ttf")}');
      font-weight: 600; font-style: normal;
    }}

    :root {{ --ink: #24242B; --ink-soft: #69665F; --gold: #8C6B2E; --paper: #FFFDF8; --line: #E8E2D6; }}

    * {{ box-sizing: border-box; }}
    html {{ background: var(--paper); }}
    body {{ margin: 0; font-family: 'Source Serif 4', serif; color: var(--ink); font-size: 11.5pt; }}

    @page {{
      size: 6in 9in;
      margin: 0.9in 0.85in 0.95in;
      background: var(--paper);
      @bottom-center {{
        content: counter(page);
        font-family: 'IBM Plex Mono'; font-size: 8.5pt; color: var(--ink-soft);
      }}
    }}
    @page cover {{ margin: 0; @bottom-center {{ content: ''; }} }}
    @page front {{ @bottom-center {{ content: counter(page, lower-roman); font-family: 'IBM Plex Mono'; font-size: 8.5pt; color: var(--ink-soft); }} }}
    @page chapter {{
      @top-center {{
        content: string(running-title);
        font-family: 'IBM Plex Mono'; font-size: 7.5pt; letter-spacing: 0.08em;
        text-transform: uppercase; color: var(--ink-soft);
      }}
    }}

    /* ===== Cover ===== */
    .cover {{
      page: cover;
      width: 6in; height: 9in;
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      text-align: center;
      background: var(--paper);
      border: 10px solid var(--paper);
      position: relative;
    }}
    .cover::before {{
      content: '';
      position: absolute; top: 0.55in; left: 0.55in; right: 0.55in; bottom: 0.55in;
      border: 1.2pt solid var(--line);
    }}
    .cover-mark {{
      width: 46pt; height: 56pt; border: 2.2pt solid var(--gold); border-radius: 50%;
      margin-bottom: 6pt; position: relative;
    }}
    .cover-mark::after {{
      content: ''; position: absolute; left: 50%; bottom: -14pt; transform: translateX(-50%);
      width: 2.2pt; height: 14pt; background: var(--gold);
    }}
    .cover-title {{ font-family: 'Fraunces'; font-weight: 560; font-size: 40pt; margin: 22pt 0 4pt; letter-spacing: -0.01em; }}
    .cover-rule {{ width: 60pt; height: 1.6pt; background: var(--gold); margin: 10pt 0; }}
    .cover-volume {{ font-family: 'IBM Plex Mono'; font-weight: 600; font-size: 13pt; letter-spacing: 0.12em; text-transform: uppercase; color: var(--gold); margin-bottom: 4pt; }}
    .cover-range {{ font-family: 'Source Serif 4'; font-style: italic; font-size: 12.5pt; color: var(--ink-soft); margin-bottom: 40pt; }}
    .cover-author {{ font-family: 'IBM Plex Mono'; font-size: 9pt; letter-spacing: 0.08em; text-transform: uppercase; color: var(--ink-soft); }}

    /* ===== Front matter ===== */
    .front {{ page: front; page-break-before: always; }}
    .front-title {{ font-family: 'Fraunces'; font-weight: 560; font-size: 19pt; margin: 0 0 16pt; }}
    .front p {{ line-height: 1.7; margin: 0 0 12pt; }}
    .ethos-line {{ font-style: italic; color: var(--ink-soft); }}

    /* ===== Table of contents ===== */
    .toc {{ page-break-before: always; }}
    .toc-title {{ font-family: 'Fraunces'; font-weight: 560; font-size: 19pt; margin: 0 0 20pt; }}
    .toc-entry {{
      display: flex; align-items: baseline; gap: 6pt;
      font-size: 10.5pt; margin-bottom: 9pt;
      text-decoration: none; color: var(--ink);
    }}
    .toc-day {{ font-family: 'IBM Plex Mono'; font-size: 8pt; color: var(--gold); flex: 0 0 auto; min-width: 30pt; }}
    .toc-entry-title {{ flex: 0 1 auto; }}
    .toc-leader {{ flex: 1 1 auto; border-bottom: 0.75pt dotted var(--line); margin: 0 4pt 2pt; }}
    .toc-page {{ text-decoration: none; }}
    .toc-page::after {{ content: target-counter(attr(href), page); font-family: 'IBM Plex Mono'; font-size: 9pt; color: var(--ink-soft); }}

    /* ===== Chapters ===== */
    .chapter {{ page: chapter; page-break-before: always; }}
    .chapter-eyebrow {{ font-family: 'IBM Plex Mono'; font-size: 8.5pt; letter-spacing: 0.1em; text-transform: uppercase; color: var(--gold); margin-bottom: 8pt; }}
    /* content(text) captures the element's own rendered text live — the
       running header always matches what's actually on the page, with no
       need to re-serialize the title into a second, error-prone copy. */
    .chapter-title {{ font-family: 'Fraunces'; font-weight: 560; font-size: 21pt; line-height: 1.15; margin: 0 0 6pt; string-set: running-title content(text); }}
    .chapter-themes {{ font-family: 'IBM Plex Mono'; font-size: 7.5pt; letter-spacing: 0.06em; text-transform: uppercase; color: var(--ink-soft); margin-bottom: 16pt; }}
    .chapter-image {{ width: 100%; max-height: 2.6in; object-fit: cover; border-radius: 3pt; margin-bottom: 16pt; }}

    .entry-body {{ line-height: 1.65; }}
    .entry-body p {{ margin: 0 0 9pt; text-align: left; }}
    .entry-body p.pause {{ margin-bottom: 15pt; }}
    .entry-body p.sequence {{ line-height: 1.4; }}
    .entry-body .mirror-marker, .entry-body .think-marker {{
      font-family: 'IBM Plex Mono'; text-align: center; text-transform: uppercase;
      color: var(--gold); letter-spacing: 0.12em; font-size: 9pt;
      margin: 22pt 0 14pt; padding: 8pt 0; border-top: 0.75pt solid var(--line); border-bottom: 0.75pt solid var(--line);
    }}
    .entry-body .think-marker {{ text-align: left; border: none; color: var(--ink-soft); font-size: 8pt; margin: 12pt 0 6pt; padding: 0; }}
    .closing-question {{
      font-family: 'Fraunces'; font-style: italic; font-weight: 500; font-size: 15pt; line-height: 1.4;
      margin: 20pt 0 0; padding-top: 12pt; border-top: 1.2pt solid var(--gold);
    }}
    """


def render_cover(volume_num, first_day, last_day):
    return f"""
    <section class="cover">
      <div class="cover-mark" aria-hidden="true"></div>
      <div class="cover-title">The Daily Mirror</div>
      <div class="cover-rule"></div>
      <div class="cover-volume">Volume {volume_num}</div>
      <div class="cover-range">Days {first_day}&ndash;{last_day}</div>
      <div class="cover-author">{escape_html(AUTHOR)}</div>
    </section>
    """


def render_front_matter():
    return f"""
    <section class="front">
      <div class="front-title">About this book</div>
      <p>{escape_html(ABOUT)}</p>
      <p class="ethos-line">&ldquo;{escape_html(ETHOS)}&rdquo;</p>
    </section>
    """


def render_toc(entries):
    rows = []
    for e in entries:
        anchor = f"day-{e['day']}"
        rows.append(f"""
          <div class="toc-entry">
            <span class="toc-day">DAY {e['day']}</span>
            <span class="toc-entry-title">{escape_html(e['title'])}</span>
            <span class="toc-leader"></span>
            <a class="toc-page" href="#{anchor}"></a>
          </div>
        """)
    return f"""
    <section class="toc">
      <div class="toc-title">Contents</div>
      {''.join(rows)}
    </section>
    """


def render_chapter(entry):
    anchor = f"day-{entry['day']}"
    meta_parts = [f"Day {entry['day']}"]
    if entry.get("date"):
        meta_parts.append(format_date(entry["date"]))
    meta = " · ".join(meta_parts)  # a literal character, not an HTML entity —
    # escape_html() below only touches &/</>, so this survives untouched
    # instead of round-tripping through an entity and getting re-escaped.
    themes_html = format_themes(entry.get("themes")) if entry.get("themes") else ""
    image_html = ""
    if entry.get("image"):
        img_path = (ROOT / entry["image"]).resolve()
        if img_path.exists():
            image_html = f'<img class="chapter-image" src="{img_path.as_uri()}" alt="">'
    body_html = render_body(entry.get("body", ""), entry.get("closing_question", ""))
    closing_html = ""
    if entry.get("closing_question"):
        closing_html = f'<p class="closing-question">{escape_html(entry["closing_question"])}</p>'
    return f"""
    <section class="chapter" id="{anchor}">
      <div class="chapter-eyebrow">{escape_html(meta)}</div>
      <h1 class="chapter-title">{escape_html(entry['title'])}</h1>
      {f'<div class="chapter-themes">{escape_html(themes_html)}</div>' if themes_html else ''}
      {image_html}
      <div class="entry-body">{body_html}</div>
      {closing_html}
    </section>
    """


def build_volume_html(entries, volume_num, first_day, last_day):
    chapters = "".join(render_chapter(e) for e in entries)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>The Daily Mirror — Volume {volume_num}</title>
<meta name="author" content="{escape_attr(AUTHOR)}">
<style>{build_css()}</style>
</head>
<body>
{render_cover(volume_num, first_day, last_day)}
{render_front_matter()}
{render_toc(entries)}
{chapters}
</body>
</html>"""


def generate_volume(entries, volume_num):
    start = (volume_num - 1) * VOLUME_SIZE
    end = start + VOLUME_SIZE
    volume_entries = entries[start:end]
    first_day = volume_entries[0]["day"]
    last_day = volume_entries[-1]["day"]
    html = build_volume_html(volume_entries, volume_num, first_day, last_day)
    BACKUPS_DIR.mkdir(exist_ok=True)
    out_path = BACKUPS_DIR / f"the-daily-mirror-volume-{volume_num}.pdf"
    HTML(string=html, base_url=str(ROOT)).write_pdf(out_path)
    return out_path


def main():
    entries = json.loads(ENTRIES_JSON.read_text(encoding="utf-8"))
    entries = sorted(entries, key=lambda e: int(e["day"]))
    count = len(entries)
    ready_volumes = count // VOLUME_SIZE  # 100 entries -> volume 1 ready, 250 -> volumes 1-2 ready

    if ready_volumes == 0:
        print(f"{count}/{VOLUME_SIZE} entries — no volume ready yet.")
        return

    made_any = False
    for vol in range(1, ready_volumes + 1):
        out_path = BACKUPS_DIR / f"the-daily-mirror-volume-{vol}.pdf"
        if out_path.exists():
            continue
        path = generate_volume(entries, vol)
        print(f"Wrote {path}")
        made_any = True

    if not made_any:
        print(f"All {ready_volumes} ready volume(s) already exist — nothing to do.")


if __name__ == "__main__":
    main()
